**CS359 Assignment**

Question 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("./MA201_marks.csv")

In [3]:
marks_details = dataset.iloc[:, -5:]

In [4]:
print(marks_details)

     Q1  Q2  Asgn  MT     ET
0   9.5   8    15  25  38.52
1   8.5   5    15  19  39.51
2   9.5   8    15  20  34.07
3   5.5   5    14  16  36.05
4   7.0   4    14  18  38.52
..  ...  ..   ...  ..    ...
64  3.5   0     8   2   3.95
65  2.0   0     9   3   8.40
66  1.5   1     9   1   6.42
67  0.5   1     9   0   5.43
68  4.0   4     9   3   0.99

[69 rows x 5 columns]


In [5]:
x = marks_details.iloc[:, :-1].values
y = marks_details.iloc[:, -1].values

In [6]:
print("Features: ", x)
print("Target: ", y)

Features:  [[ 9.5  8.  15.  25. ]
 [ 8.5  5.  15.  19. ]
 [ 9.5  8.  15.  20. ]
 [ 5.5  5.  14.  16. ]
 [ 7.   4.  14.  18. ]
 [ 4.5  1.  15.  22. ]
 [ 4.   5.  14.  14. ]
 [ 7.   5.  15.  16. ]
 [ 7.   4.  15.  20. ]
 [10.   6.  15.  16. ]
 [ 4.5  7.  15.   9. ]
 [ 8.5  4.  15.  20. ]
 [ 5.5  8.  15.  16. ]
 [ 4.   4.  13.  10. ]
 [ 4.   3.  15.  15. ]
 [ 3.   6.  14.  11. ]
 [ 8.5  2.  14.  13. ]
 [ 5.5  7.  13.   7. ]
 [ 4.5  0.  13.  15. ]
 [ 6.5  4.  15.  11. ]
 [ 6.   6.  15.   3. ]
 [ 5.   2.  15.  14. ]
 [ 8.   2.  15.   9. ]
 [ 3.   4.  12.  14. ]
 [ 3.   1.  12.   7. ]
 [ 3.5  1.  12.   6. ]
 [ 4.   0.  12.   7. ]
 [ 3.   2.  12.  11. ]
 [ 4.5  3.  12.  11. ]
 [ 3.5  3.  12.   5. ]
 [ 5.5  1.  12.  14. ]
 [ 3.   4.  14.  10. ]
 [ 5.5  3.  12.  14. ]
 [ 6.   4.  12.   3. ]
 [ 4.5  1.  12.  15. ]
 [ 5.5  7.  12.   5. ]
 [ 6.5  2.  11.   9. ]
 [ 2.   1.  11.   5. ]
 [ 3.5  3.  13.   5. ]
 [ 3.5  4.  11.   6. ]
 [ 2.   0.  13.  11. ]
 [ 5.5  3.  11.   9. ]
 [ 3.5  3.  11.   6. ]


In [7]:
x_mean = [np.sum(i)/4 for i in x]

In [8]:
marks_details['x_mean'] = x_mean

In [9]:
dataset = marks_details

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(np.array(x_mean).reshape(69, 1), y.reshape(69, 1), test_size=0.2, random_state=42)

In [12]:
x_mean = x_train

In [13]:
print("X_Mean: ", x_mean)

X_Mean:  [[ 5.   ]
 [ 8.125]
 [ 5.   ]
 [ 7.375]
 [ 6.75 ]
 [ 6.25 ]
 [ 9.375]
 [ 8.125]
 [ 5.875]
 [ 7.625]
 [10.75 ]
 [ 4.125]
 [ 6.5  ]
 [ 4.5  ]
 [ 5.75 ]
 [ 9.125]
 [ 3.75 ]
 [ 6.125]
 [ 5.625]
 [ 6.125]
 [ 7.75 ]
 [ 6.5  ]
 [10.125]
 [ 8.125]
 [11.5  ]
 [ 5.25 ]
 [ 9.25 ]
 [ 7.125]
 [ 4.375]
 [ 2.625]
 [ 8.5  ]
 [ 7.   ]
 [ 7.125]
 [ 5.75 ]
 [ 5.75 ]
 [ 5.75 ]
 [ 4.   ]
 [ 3.875]
 [11.875]
 [ 8.625]
 [ 3.5  ]
 [ 3.125]
 [ 4.75 ]
 [ 5.875]
 [ 7.875]
 [ 3.375]
 [11.875]
 [ 5.125]
 [ 9.   ]
 [13.125]
 [ 8.25 ]
 [ 7.5  ]
 [ 5.125]
 [ 9.25 ]
 [ 6.   ]]


In [14]:
X = np.concatenate((np.ones((x_train.shape[0], 1)), x_train), axis=1)

In [15]:
print(X, X.shape)

[[ 1.     5.   ]
 [ 1.     8.125]
 [ 1.     5.   ]
 [ 1.     7.375]
 [ 1.     6.75 ]
 [ 1.     6.25 ]
 [ 1.     9.375]
 [ 1.     8.125]
 [ 1.     5.875]
 [ 1.     7.625]
 [ 1.    10.75 ]
 [ 1.     4.125]
 [ 1.     6.5  ]
 [ 1.     4.5  ]
 [ 1.     5.75 ]
 [ 1.     9.125]
 [ 1.     3.75 ]
 [ 1.     6.125]
 [ 1.     5.625]
 [ 1.     6.125]
 [ 1.     7.75 ]
 [ 1.     6.5  ]
 [ 1.    10.125]
 [ 1.     8.125]
 [ 1.    11.5  ]
 [ 1.     5.25 ]
 [ 1.     9.25 ]
 [ 1.     7.125]
 [ 1.     4.375]
 [ 1.     2.625]
 [ 1.     8.5  ]
 [ 1.     7.   ]
 [ 1.     7.125]
 [ 1.     5.75 ]
 [ 1.     5.75 ]
 [ 1.     5.75 ]
 [ 1.     4.   ]
 [ 1.     3.875]
 [ 1.    11.875]
 [ 1.     8.625]
 [ 1.     3.5  ]
 [ 1.     3.125]
 [ 1.     4.75 ]
 [ 1.     5.875]
 [ 1.     7.875]
 [ 1.     3.375]
 [ 1.    11.875]
 [ 1.     5.125]
 [ 1.     9.   ]
 [ 1.    13.125]
 [ 1.     8.25 ]
 [ 1.     7.5  ]
 [ 1.     5.125]
 [ 1.     9.25 ]
 [ 1.     6.   ]] (55, 2)


In [16]:
w_cap = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_train)

In [17]:
print(w_cap)

[[-4.32619971]
 [ 3.36149   ]]


In [18]:
print(X.shape , w_cap.shape)

(55, 2) (2, 1)


In [19]:
y_pred = np.dot(X, w_cap)

In [20]:
print("Y_pred: ", y_pred)

Y_pred:  [[12.48125028]
 [22.98590652]
 [12.48125028]
 [20.46478902]
 [18.36385777]
 [16.68311277]
 [27.18776902]
 [22.98590652]
 [15.42255403]
 [21.30516152]
 [31.80981776]
 [ 9.53994653]
 [17.52348527]
 [10.80050528]
 [15.00236778]
 [26.34739652]
 [ 8.27938778]
 [16.26292652]
 [14.58218153]
 [16.26292652]
 [21.72534777]
 [17.52348527]
 [29.70888651]
 [22.98590652]
 [34.33093526]
 [13.32162278]
 [26.76758277]
 [19.62441652]
 [10.38031903]
 [ 4.49771153]
 [24.24646527]
 [19.20423027]
 [19.62441652]
 [15.00236778]
 [15.00236778]
 [15.00236778]
 [ 9.11976028]
 [ 8.69957403]
 [35.59149401]
 [24.66665152]
 [ 7.43901528]
 [ 6.17845653]
 [11.64087778]
 [15.42255403]
 [22.14553402]
 [ 7.01882903]
 [35.59149401]
 [12.90143653]
 [25.92721027]
 [39.79335651]
 [23.40609277]
 [20.88497527]
 [12.90143653]
 [26.76758277]
 [15.84274027]]


In [21]:
y_real = y_train

In [22]:
print(y_real , y_pred)

[[ 0.99]
 [21.73]
 [ 6.91]
 [23.21]
 [ 4.94]
 [10.86]
 [24.2 ]
 [20.25]
 [17.28]
 [20.74]
 [37.04]
 [ 3.95]
 [13.83]
 [11.85]
 [12.84]
 [25.19]
 [13.33]
 [18.77]
 [29.14]
 [15.8 ]
 [32.1 ]
 [10.37]
 [36.05]
 [34.07]
 [34.07]
 [ 5.93]
 [36.54]
 [17.28]
 [ 4.94]
 [ 5.43]
 [27.65]
 [24.69]
 [12.84]
 [28.15]
 [13.83]
 [28.64]
 [12.84]
 [ 6.91]
 [26.67]
 [19.75]
 [ 8.4 ]
 [ 6.42]
 [22.72]
 [31.6 ]
 [ 8.4 ]
 [ 3.95]
 [39.51]
 [ 6.42]
 [26.17]
 [34.07]
 [21.73]
 [32.1 ]
 [ 6.42]
 [24.69]
 [ 3.46]] [[12.48125028]
 [22.98590652]
 [12.48125028]
 [20.46478902]
 [18.36385777]
 [16.68311277]
 [27.18776902]
 [22.98590652]
 [15.42255403]
 [21.30516152]
 [31.80981776]
 [ 9.53994653]
 [17.52348527]
 [10.80050528]
 [15.00236778]
 [26.34739652]
 [ 8.27938778]
 [16.26292652]
 [14.58218153]
 [16.26292652]
 [21.72534777]
 [17.52348527]
 [29.70888651]
 [22.98590652]
 [34.33093526]
 [13.32162278]
 [26.76758277]
 [19.62441652]
 [10.38031903]
 [ 4.49771153]
 [24.24646527]
 [19.20423027]
 [19.62441652]
 [15.0023

In [23]:
training_loss_mse = np.mean((y_real - y_pred)**2)
print("Training Loss: ", training_loss_mse)

Training Loss:  51.068804123249144


In [24]:
X = np.concatenate((np.ones((x_test.shape[0], 1)), x_test), axis=1)
print(X, X.shape)


[[ 1.     8.5  ]
 [ 1.    14.375]
 [ 1.     6.5  ]
 [ 1.    10.75 ]
 [ 1.     5.875]
 [ 1.     8.125]
 [ 1.     8.875]
 [ 1.     6.25 ]
 [ 1.     7.25 ]
 [ 1.    11.125]
 [ 1.     7.75 ]
 [ 1.    11.75 ]
 [ 1.     5.875]
 [ 1.    10.625]] (14, 2)


In [25]:
w_cap = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_test)
print(w_cap)

[[-6.98665332]
 [ 3.64734598]]


In [26]:
y_pred = np.dot(X, w_cap)
print(y_pred)

[[24.01578749]
 [45.44394511]
 [16.72109554]
 [32.22231594]
 [14.4415043 ]
 [22.64803275]
 [25.38354223]
 [15.80925904]
 [19.45660502]
 [33.59007068]
 [21.28027801]
 [35.86966192]
 [14.4415043 ]
 [31.76639769]]


In [27]:
y_real = y_test

In [28]:
testing_loss = np.mean((y_real - y_pred)**2)
print("Testing Loss:",testing_loss)

Testing Loss: 64.51571635393704


In [29]:
sigma_square = np.var(y)
print(sigma_square)

128.28059924385636


In [30]:
expected_training_loss = sigma_square - w_cap.shape[0]*sigma_square / x.shape[0]
print("Expected Training Loss: ", expected_training_loss)

Expected Training Loss:  124.56232100490399


In [31]:
expected_testing_loss = sigma_square + w_cap.shape[0]*sigma_square / x.shape[0]
print("Expected Testing Loss: ", expected_testing_loss)

Expected Testing Loss:  131.99887748280872
