**CS359 Assignment**

Question 2

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv(r"./Position_Salaries.csv")

In [3]:
print(dataset)

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000


In [4]:
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print(x, y)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] [  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [6]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((7, 1), (3, 1), (7,), (3,))

In [7]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [8]:
polynomial_regression = PolynomialFeatures(degree=3)

In [9]:
print(polynomial_regression.get_params())
print()

x_poly = polynomial_regression.fit_transform(x_train)
print(x_poly)

{'degree': 3, 'include_bias': True, 'interaction_only': False, 'order': 'C'}

[[   1.   10.  100. 1000.]
 [   1.    2.    4.    8.]
 [   1.    7.   49.  343.]
 [   1.    8.   64.  512.]
 [   1.    4.   16.   64.]
 [   1.    1.    1.    1.]
 [   1.    6.   36.  216.]]


In [10]:
w_cap = np.linalg.inv(x_poly.T.dot(x_poly)).dot(x_poly.T).dot(y_train)
print(w_cap)

[-95193.69887098 162284.42075002 -45277.89957551   3987.6776068 ]


In [11]:
y_pred = np.dot(x_poly , w_cap)
print(y_pred)

[987538.15787992  80164.96518145 189953.58631223 346987.02897908
  84708.9577563   25800.49991034 109846.80398003]


In [12]:
y_real = y_train

In [13]:
training_loss = np.mean((y_real-y_pred)**2)
print("Training Loss:",training_loss)

Training Loss: 768144027.3075281


In [14]:
x_poly = polynomial_regression.fit_transform(x_test)
print(x_poly)

[[  1.   3.   9.  27.]
 [  1.   9.  81. 729.]
 [  1.   5.  25. 125.]]


In [15]:
w_cap = np.linalg.inv(x_poly.T.dot(x_poly)).dot(x_poly.T).dot(y_test)
print(w_cap)

[-4.31959961e+06  6.78471680e+05 -1.93603516e+03 -1.54582977e+03]


In [16]:
y_pred = np.dot(x_poly , w_cap)
print(y_pred)

[-2343346.29058838   502916.75567627 -1168870.8114624 ]


In [17]:
y_real = y_test

In [18]:
testing_loss = np.mean((y_real - y_pred)**2)
print("Testing Loss: ", testing_loss)

Testing Loss:  2470530817453.033


In [19]:
print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [20]:
sigma_square = np.var(y)
print(sigma_square)

80662250000.0


In [21]:
expected_training_loss = sigma_square - w_cap.shape[0]*sigma_square / x.shape[0]
print("Expected Training Loss:",expected_training_loss)

Expected Training Loss: 48397350000.0


In [22]:
expected_testing_loss = sigma_square + w_cap.shape[0]*sigma_square / x.shape[0]
print("Expected Testing Loss:",expected_testing_loss)

Expected Testing Loss: 112927150000.0
